package com.studentmgmt.model;

/**
 * Domain model representing a Student entity.
 * Fields map directly to the `students` table in PostgreSQL.
 */
public class Student {

    /** Primary key — auto-generated by the DB (SERIAL). */
    private Integer id;

    /** Full name of the student. */
    private String name;

    /** Unique email address. */
    private String email;

    /** Course / programme the student is enrolled in. */
    private String course;

    // ── Constructors ──────────────────────────────────────────────────────────

    public Student() {}

    public Student(Integer id, String name, String email, String course) {
        this.id     = id;
        this.name   = name;
        this.email  = email;
        this.course = course;
    }

    /** Convenience constructor for create/update (no id needed). */
    public Student(String name, String email, String course) {
        this.name   = name;
        this.email  = email;
        this.course = course;
    }

    // ── Getters & Setters ─────────────────────────────────────────────────────

    public Integer getId()             { return id; }
    public void    setId(Integer id)   { this.id = id; }

    public String  getName()           { return name; }
    public void    setName(String n)   { this.name = n; }

    public String  getEmail()          { return email; }
    public void    setEmail(String e)  { this.email = e; }

    public String  getCourse()         { return course; }
    public void    setCourse(String c) { this.course = c; }

    @Override
    public String toString() {
        return "Student{id=" + id + ", name='" + name + "', email='"
               + email + "', course='" + course + "'}";
    }
}
