package com.studentmgmt.repository;

import com.studentmgmt.model.Student;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.List;
import java.util.Optional;

/**
 * JDBC implementation of {@link StudentRepository}.
 *
 * All SQL is written by hand — no ORM is used.
 * {@link JdbcTemplate} handles connection management and exception translation.
 */
@Repository
public class StudentRepositoryImpl implements StudentRepository {

    private final JdbcTemplate jdbcTemplate;

    // ── RowMapper ─────────────────────────────────────────────────────────────
    /**
     * Maps a single ResultSet row to a {@link Student} object.
     * Declared as a field so it can be reused across all query methods.
     */
    private final RowMapper<Student> studentRowMapper = (rs, rowNum) -> new Student(
            rs.getInt("id"),
            rs.getString("name"),
            rs.getString("email"),
            rs.getString("course")
    );

    public StudentRepositoryImpl(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    // ── CRUD Operations ───────────────────────────────────────────────────────

    /**
     * Insert a new student row and return the persisted entity (with auto-generated id).
     */
    @Override
    public Student save(Student student) {
        final String SQL = "INSERT INTO students (name, email, course) VALUES (?, ?, ?)";

        // KeyHolder captures the SERIAL id generated by PostgreSQL
        KeyHolder keyHolder = new GeneratedKeyHolder();

        jdbcTemplate.update(connection -> {
            PreparedStatement ps = connection.prepareStatement(SQL, new String[]{"id"});
            ps.setString(1, student.getName());
            ps.setString(2, student.getEmail());
            ps.setString(3, student.getCourse());
            return ps;
        }, keyHolder);

        // Retrieve the generated id and set it on the returned object
        Number generatedId = keyHolder.getKey();
        student.setId(generatedId != null ? generatedId.intValue() : null);

        return student;
    }

    /**
     * Fetch all student rows.
     */
    @Override
    public List<Student> findAll() {
        final String SQL = "SELECT id, name, email, course FROM students ORDER BY id ASC";
        return jdbcTemplate.query(SQL, studentRowMapper);
    }

    /**
     * Fetch a single student by primary key.
     * Returns {@link Optional#empty()} when the id is not found (no exception from JDBC layer).
     */
    @Override
    public Optional<Student> findById(Integer id) {
        final String SQL = "SELECT id, name, email, course FROM students WHERE id = ?";

        // query() returns a list; map to Optional instead of throwing on empty
        List<Student> results = jdbcTemplate.query(SQL, studentRowMapper, id);
        return results.stream().findFirst();
    }

    /**
     * Update name, email, and course for an existing student.
     *
     * @return 1 if the row was updated; 0 if no row matched the given id
     */
    @Override
    public int update(Integer id, Student student) {
        final String SQL = "UPDATE students SET name = ?, email = ?, course = ? WHERE id = ?";
        return jdbcTemplate.update(SQL,
                student.getName(),
                student.getEmail(),
                student.getCourse(),
                id
        );
    }

    /**
     * Delete the student row with the given primary key.
     *
     * @return 1 if the row was deleted; 0 if no row matched
     */
    @Override
    public int delete(Integer id) {
        final String SQL = "DELETE FROM students WHERE id = ?";
        return jdbcTemplate.update(SQL, id);
    }
}
